# Generated by Django 4.2.14 on 2024-07-22 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0002_alter_members_email_alter_members_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='RssURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2000)),
                ('members', models.ManyToManyField(to='members.members')),
            ],
        ),
        migrations.CreateModel(
            name='RssData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rss.rssurl')),
            ],
        ),
    ]
