# Generated by Django 4.2.14 on 2024-07-23 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RSSFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('link', models.URLField(max_length=2000)),
                ('description', models.CharField(max_length=100)),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rss.rssurl')),
            ],
        ),
        migrations.CreateModel(
            name='RssPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('link', models.URLField(max_length=2000)),
                ('pubDate', models.DateTimeField()),
                ('description', models.CharField(max_length=1000)),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rss.rssfeed')),
            ],
        ),
        migrations.DeleteModel(
            name='RssData',
        ),
    ]
