# Generated by Django 4.2.14 on 2024-07-23 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0002_rssfeed_rsspost_delete_rssdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rsspost',
            old_name='url',
            new_name='rssFeed',
        ),
    ]
