# Generated by Django 4.2.14 on 2024-07-23 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0003_rename_url_rsspost_rssfeed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rsspost',
            old_name='rssFeed',
            new_name='rss_feed',
        ),
    ]
