# Generated by Django 4.2.14 on 2024-07-23 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0004_rename_rssfeed_rsspost_rss_feed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rsspost',
            old_name='pubDate',
            new_name='pub_date',
        ),
    ]
