# Generated by Django 4.2.14 on 2024-07-23 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0005_rename_pubdate_rsspost_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rssurl',
            name='url',
            field=models.URLField(max_length=2000, unique=True),
        ),
    ]
