# Generated by Django 4.2.14 on 2024-07-23 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0006_alter_rssurl_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rsspost',
            name='pub_date',
        ),
    ]
