# Generated by Django 4.2.14 on 2024-07-23 04:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0007_remove_rsspost_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='rsspost',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
