# Generated by Django 4.2.14 on 2024-07-29 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0008_rsspost_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rssurl',
            name='members',
        ),
    ]
