# Generated by Django 4.2.14 on 2024-07-29 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0009_remove_rssurl_members'),
        ('members', '0002_alter_members_email_alter_members_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='rssURLs',
            field=models.ManyToManyField(to='rss.rssurl'),
        ),
    ]
